# Generated by Django 4.2.5 on 2024-01-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
    ]
